# Generated by Django 2.1.7 on 2019-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('channel_name', models.CharField(max_length=200)),
                ('wiki', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
