# Generated by Django 2.1.7 on 2019-04-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indiatoday',
            new_name='Indiatv',
        ),
    ]
