# Generated by Django 2.1.7 on 2019-04-09 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190328_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Firstpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Hindustan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IndexTop10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_keyword', models.TextField()),
                ('db_frequency', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Indianexpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Indiatoday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ndtv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Oneindia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Republic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Thehindu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Zeenews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
