# Generated by Django 2.1.7 on 2019-05-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190418_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anchor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='count',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='news_channel',
            options={'ordering': ['-id']},
        ),
    ]
