# Generated by Django 2.1.7 on 2019-05-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20190523_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident', models.FloatField()),
                ('health', models.FloatField()),
                ('world', models.FloatField()),
                ('lifestyle', models.FloatField()),
                ('pollution', models.FloatField()),
                ('security', models.FloatField()),
                ('education', models.FloatField()),
                ('entertainment', models.FloatField()),
                ('sports', models.FloatField()),
                ('politics', models.FloatField()),
                ('business', models.FloatField()),
                ('terrorism', models.FloatField()),
                ('crime', models.FloatField()),
                ('employment', models.FloatField()),
                ('technology', models.FloatField()),
            ],
        ),
    ]
