# Generated by Django 2.1.7 on 2019-05-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_categoryratio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryRatio',
        ),
    ]
