# Generated by Django 2.1.7 on 2019-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_delete_categoryratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
